<?php

return [
    'admin_email' => 'info@techtires.ru',
    'shop_name' => 'Armour-shina',
	'shop_description' => 'Шины для спецтехники и минипогрузчиков, диски, фильтры',
	'og_logo' => 'Logo_round_1200.jpg',
    'pagination' => 20,
    'smtp_host' => config_env('SMTP_HOST', ''),
    'smtp_port' => config_env('SMTP_PORT', '587'),
    'smtp_protocol' => config_env('SMTP_PROTOCOL', ''),
    'smtp_login' => config_env('SMTP_USERNAME', ''),
    'smtp_password' => config_env('SMTP_PASSWORD', ''),
    'img_width' => 600,
    'img_height' => 600,
	'mini_img_width' => 250,
    'mini_img_height' => 250,
    'gallery_width' => 600,
    'gallery_height' => 600,
	'mini_gallery_width' => 250,
    'mini_gallery_height' => 250,
	'img_width_brand' => 250,
    'img_height_brand' => 250,
	'img_width_filter' => 250,
    'img_height_filter' => 250,
	'img_width_content' => 1400,
    'img_height_content' => 460,
	'ftp_server' => config_env('FTP_HOST', ''),
	'ftp_login' => config_env('FTP_USERNAME', ''),
    'ftp_pass' => config_env('FTP_PASSWORD', ''),
	'ftp_port' => config_env('FTP_PORT', '21'),
	'time_active_link' => '3600',
	'sql_user' => config_env('DB_USERNAME', ''),
	'sql_pass' => config_env('DB_PASSWORD', ''),
    'sql_db' => config_env('DB_DATABASE', ''),
	'sql_host' => config_env('DB_HOST', '127.0.0.1:3306'),
];
