<?php

return [
    'admin_email' => 'info@techtires.ru',
    'shop_name' => 'Armour-shina',
	'shop_description' => 'Шины для спецтехники и минипогрузчиков, диски, фильтры',
	'og_logo' => 'Logo_round_1200.jpg',
    'pagination' => 20,
    'smtp_host' => '88.212.206.67',
    'smtp_port' => '587',
    'smtp_protocol' => '',
    'smtp_login' => 'info@techtires.ru',
    'smtp_password' => 'oE3rH6sG1d',
    'img_width' => 600,
    'img_height' => 600,
	'mini_img_width' => 250,
    'mini_img_height' => 250,
    'gallery_width' => 600,
    'gallery_height' => 600,
	'mini_gallery_width' => 250,
    'mini_gallery_height' => 250,
	'img_width_brand' => 250,
    'img_height_brand' => 250,
	'img_width_filter' => 250,
    'img_height_filter' => 250,
	'img_width_content' => 1400,
    'img_height_content' => 460,
	'ftp_server' => 'grass.gohost.ru',
	'ftp_login' => 'cl347323_techtires',
    'ftp_pass' => 'cX2oL0iB8c',
	'ftp_port' => '21',
	'time_active_link' => '3600',
	'sql_user' => 'cl347323_techtires',
	'sql_pass' => 'tK1zW5jK7w',
    'sql_db' => 'cl347323_techtires',
	'sql_host' => '127.0.0.1:3311',
];